// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwJEBAMGt17g6LCJ479LbeQYRJ8XV2mt4',
    appId: '1:21600026206:web:dc204cddc7979398933ecf',
    messagingSenderId: '21600026206',
    projectId: 'fooddelivery-86fba',
    authDomain: 'fooddelivery-86fba.firebaseapp.com',
    databaseURL: 'https://fooddelivery-86fba-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivery-86fba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu0sTf1K95xLKr9n6glu68p9tGGU7cCRA',
    appId: '1:21600026206:android:c1b6e0675840aa46933ecf',
    messagingSenderId: '21600026206',
    projectId: 'fooddelivery-86fba',
    databaseURL: 'https://fooddelivery-86fba-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivery-86fba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO3GACjsslNmYSB2DfChA-YYZ2__uIeQ0',
    appId: '1:21600026206:ios:614902c0e6cbc4f1933ecf',
    messagingSenderId: '21600026206',
    projectId: 'fooddelivery-86fba',
    databaseURL: 'https://fooddelivery-86fba-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivery-86fba.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO3GACjsslNmYSB2DfChA-YYZ2__uIeQ0',
    appId: '1:21600026206:ios:614902c0e6cbc4f1933ecf',
    messagingSenderId: '21600026206',
    projectId: 'fooddelivery-86fba',
    databaseURL: 'https://fooddelivery-86fba-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivery-86fba.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwJEBAMGt17g6LCJ479LbeQYRJ8XV2mt4',
    appId: '1:21600026206:web:c27bf5d04e3ac328933ecf',
    messagingSenderId: '21600026206',
    projectId: 'fooddelivery-86fba',
    authDomain: 'fooddelivery-86fba.firebaseapp.com',
    databaseURL: 'https://fooddelivery-86fba-default-rtdb.firebaseio.com',
    storageBucket: 'fooddelivery-86fba.appspot.com',
  );
}
